# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  mongodb-sharded:
    image: docker.io/bitnamilegacy/mongodb-sharded:8.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-sharded
      - MONGODB_SHARDING_MODE=mongos
      - MONGODB_CFG_PRIMARY_HOST=mongodb-cfg-primary
      - MONGODB_CFG_REPLICA_SET_NAME=cfgreplicaset
      - MONGODB_REPLICA_SET_KEY=${MONGODB_REPLICA_SET_KEY}
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    networks:
      - mongodb-net
      - __BACKEND_NETWORK_PLACEHOLDER__

  mongodb-shard0-primary:
    image: docker.io/bitnamilegacy/mongodb-sharded:8.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-shard0-primary
      - MONGODB_SHARDING_MODE=shardsvr
      - MONGODB_MONGOS_HOST=mongodb-sharded
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=${MONGODB_REPLICA_SET_KEY}
      - MONGODB_REPLICA_SET_NAME=shard0
    volumes:
      - "shard0_data:/bitnami"
    networks:
      - mongodb-net

  mongodb-shard1-primary:
    image: docker.io/bitnamilegacy/mongodb-sharded:8.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-shard1-primary
      - MONGODB_SHARDING_MODE=shardsvr
      - MONGODB_MONGOS_HOST=mongodb-sharded
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=${MONGODB_REPLICA_SET_KEY}
      - MONGODB_REPLICA_SET_NAME=shard1
    volumes:
      - "shard1_data:/bitnami"
    networks:
      - mongodb-net

  mongodb-shard2-primary:
    image: docker.io/bitnamilegacy/mongodb-sharded:8.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-shard2-primary
      - MONGODB_SHARDING_MODE=shardsvr
      - MONGODB_MONGOS_HOST=mongodb-sharded
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=${MONGODB_REPLICA_SET_KEY}
      - MONGODB_REPLICA_SET_NAME=shard2
    volumes:
      - "shard2_data:/bitnami"
    networks:
      - mongodb-net

  mongodb-cfg-primary:
    image: docker.io/bitnamilegacy/mongodb-sharded:8.0
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-cfg-primary
      - MONGODB_SHARDING_MODE=configsvr
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=${MONGODB_REPLICA_SET_KEY}
      - MONGODB_REPLICA_SET_NAME=cfgreplicaset
    volumes:
      - "cfg_data:/bitnami"
    networks:
      - mongodb-net

volumes:
  shard0_data:
    driver: local
  shard1_data:
    driver: local
  shard2_data:
    driver: local
  cfg_data:
    driver: local

networks:
  mongodb-net:
    driver: bridge
  __BACKEND_NETWORK_PLACEHOLDER__:
    external: true
