# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

version: "3.9"

services:
  kafka:
    image: docker.io/bitnamilegacy/kafka:3.9
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/bitnami
    environment:
      # KRaft / Controller settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093

      # Listeners
      - KAFKA_CFG_LISTENERS=INTERNAL://:9094,CONTROLLER://:9093,LISTENER://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://:9094,CONTROLLER://:9093,LISTENER://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,LISTENER:SASL_PLAINTEXT

      # SASL / Authentication
      - KAFKA_CFG_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_CLIENT_LISTENER_NAME=LISTENER
      - KAFKA_CLIENT_USERS=kafka
      - KAFKA_CLIENT_PASSWORDS=Cuong123_A

      # Controller/Inter-broker
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL

volumes:
  kafka_data:
    driver: local
